# Generated by Django 4.1.1 on 2024-01-01 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('Invoice_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Customer_Name', models.CharField(max_length=255)),
                ('Date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(max_length=255)),
                ('quantity', models.TextField(blank=True, null=True)),
                ('unit_price', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('invoice_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.invoice')),
            ],
        ),
    ]
